import test from 'node:test';import assert from 'node:assert/strict';
import{createFirstPhonePlan,inspectFirstPhone}from'./first-phone-number.mjs';
const account='AC'+'a'.repeat(32),trunk='TK'+'b'.repeat(32),numberSid='PN'+'c'.repeat(32);
const env={LIGOU_TWILIO_ACCOUNT_SID:account,LIGOU_OPENAI_PROJECT_ID:'proj_fixture',LIGOU_PHONE_TENANT_ID:'22000000-0000-4000-8000-000000000001',LIGOU_SUPABASE_URL:'https://fixture.supabase.co',LIGOU_PHONE_NUMBER:'+14155550123',LIGOU_TWILIO_TRUNK_SID:trunk,LIGOU_TWILIO_AUTH_TOKEN:'synthetic-private-token'};
function fixture(overrides={}){const calls=[];const fetch=async(url,options)=>{calls.push({url:String(url),options});assert.equal(options.method,'GET');assert.equal(options.redirect,'error');let value;if(String(url).endsWith(account+'.json'))value={sid:account,status:'active',type:'Full'};else if(String(url).includes('IncomingPhoneNumbers'))value={incoming_phone_numbers:[{sid:numberSid,account_sid:account,phone_number:env.LIGOU_PHONE_NUMBER,capabilities:{voice:true},trunk_sid:trunk}]};else if(String(url).includes('OriginationUrls'))value={origination_urls:[{enabled:true,account_sid:account,trunk_sid:trunk,sip_url:'sip:proj_fixture@sip.api.openai.com;transport=tls'}],meta:{next_page_url:null}};else value={sid:trunk,account_sid:account,secure:true,recording:{mode:'do-not-record'},transfer_mode:'disable-all',disaster_recovery_url:null};return Response.json(overrides.transform?.(value,String(url))??value)};return{calls,fetch};}
test('planning is explicit, starts disabled and never includes credentials',()=>{const p=createFirstPhonePlan(env);assert.equal(p.status,'plan_ready');assert.equal(p.sip_uri,'sip:proj_fixture@sip.api.openai.com;transport=tls');assert.equal(p.webhook_url,'https://fixture.supabase.co/functions/v1/accept-call');assert.equal(p.binding.arguments.p_enabled,false);assert.equal(p.purchase_performed,false);assert.ok(!JSON.stringify(p).includes(env.LIGOU_TWILIO_AUTH_TOKEN));});
test('generic credentials from another business never implicitly select the account',()=>{const p=createFirstPhonePlan({TWILIO_ACCOUNT_SID:account,TWILIO_AUTH_TOKEN:'other-secret'});assert.equal(p.status,'configuration_needed');assert.ok(p.missing.includes('LIGOU_TWILIO_ACCOUNT_SID'));assert.ok(!JSON.stringify(p).includes('other-secret'));});
test('invalid identifiers and external webhook hosts are rejected before HTTP',async()=>{for(const bad of [{LIGOU_TWILIO_ACCOUNT_SID:'../another'},{LIGOU_OPENAI_PROJECT_ID:'proj_x@evil.test'},{LIGOU_SUPABASE_URL:'https://evil.test'},{LIGOU_PHONE_NUMBER:'4155550123'},{LIGOU_PHONE_TENANT_ID:'not-a-uuid'}])assert.throws(()=>createFirstPhonePlan({...env,...bad}),/invalid_/);});
test('owned number and secure single-route trunk can be inspected using GET only',async()=>{const f=fixture(),r=await inspectFirstPhone(env,f.fetch);assert.equal(r.provider_configuration_matches,true);assert.equal(r.carrier_call_verified,false);assert.equal(r.purchase_performed,false);assert.equal(f.calls.length,4);assert.ok(!JSON.stringify(r).includes(env.LIGOU_TWILIO_AUTH_TOKEN));});
test('wrong account, nonvoice number, insecure trunk and extra live routes are not ready',async()=>{for(const transform of [v=>v.sid===account?{...v,sid:'AC'+'d'.repeat(32)}:v,v=>v.incoming_phone_numbers?{incoming_phone_numbers:[{...v.incoming_phone_numbers[0],capabilities:{voice:false}}]}:v,v=>v.sid===trunk?{...v,secure:false}:v,v=>v.origination_urls?{...v,origination_urls:[...v.origination_urls,{enabled:true,sip_url:'sip:other@example.test'}]}:v,v=>v.sid===trunk?{...v,recording:{mode:'record-from-answer'}}:v]){const f=fixture({transform}),r=await inspectFirstPhone(env,f.fetch);assert.equal(r.provider_configuration_matches,false);assert.ok(r.findings.length);}});
test('provider error details and secrets are not reflected into the report',async()=>{const r=await inspectFirstPhone(env,async()=>Response.json({message:'secret '+env.LIGOU_TWILIO_AUTH_TOKEN},{status:403}));assert.equal(r.provider_configuration_matches,false);assert.ok(!JSON.stringify(r).includes(env.LIGOU_TWILIO_AUTH_TOKEN));assert.deepEqual(r.findings,['twilio_http_403']);});
test('missing preparation inputs make no network request',async()=>{let calls=0;const r=await inspectFirstPhone({},async()=>{calls++;throw Error()});assert.equal(calls,0);assert.equal(r.status,'configuration_needed');});
test('a plan without a selected number does not expose an invalid binding command',()=>{const p=createFirstPhonePlan({...env,LIGOU_PHONE_NUMBER:''});assert.equal(p.binding,null);});
