import {test,expect} from 'bun:test';
import {handlePhoneWebhook} from '../../supabase/functions/_shared/phone-webhook.ts';
import {canonicalPhoneNumber} from '../../supabase/functions/_shared/phone-number.ts';
const key=btoa('01234567890123456789012345678901');
const now=1788638400000;
const event={type:'realtime.call.incoming',data:{call_id:'rtc_fixture',sip_headers:[{name:'To',value:'"Business" <sip:+14155550123@example.test>;tag=1'},{name:'From',value:'sip:+14155550124@caller.test'},{name:'X-Private',value:'do not store'}]}};
async function request(body:unknown=event,options:{timestamp?:string;signature?:string;method?:string;signingKey?:string}={}){
 const raw=typeof body==='string'?body:JSON.stringify(body),timestamp=options.timestamp??String(now/1000),id='wh_test';
 const cryptoKey=await crypto.subtle.importKey('raw',Uint8Array.from(atob(options.signingKey??key),c=>c.charCodeAt(0)),{name:'HMAC',hash:'SHA-256'},false,['sign']);
 const mac=await crypto.subtle.sign('HMAC',cryptoKey,new TextEncoder().encode(`${id}.${timestamp}.${raw}`));
 return new Request('https://fixture.test/accept-call',{method:options.method??'POST',headers:{'content-type':'application/json','webhook-id':id,'webhook-timestamp':timestamp,'webhook-signature':options.signature??`v1,${btoa(String.fromCharCode(...new Uint8Array(mac)))}`},...(options.method==='GET'?{}:{body:raw})});
}
function deps(overrides:any={}){const rows:any[]=[];return{rows,options:{webhookSecret:'whsec_'+key,contactHashKey:key,now:()=>now,persist:async(row:any)=>{rows.push(row);return Response.json({received:true})},...overrides}};}
test('a signed call persists only its canonical destination and hashed caller',async()=>{const f=deps();const r=await handlePhoneWebhook(await request(),f.options);expect(r.status).toBe(200);expect(f.rows).toHaveLength(1);expect(f.rows[0]).toMatchObject({openai_call_id:'rtc_fixture',called_number:'+14155550123',sip_headers:{to:'+14155550123'}});expect(f.rows[0].caller_number_hash).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(f.rows)).not.toContain('+14155550124');expect(JSON.stringify(f.rows)).not.toContain('do not store');});
test('forged, stale and malformed timestamp signatures cannot persist calls',async()=>{for(const opts of [{signature:'v1,Zm9v'},{timestamp:String(now/1000-301)},{timestamp:'NaN'},{timestamp:'1e9'},{timestamp:String(now/1000+301)}]){const f=deps();expect((await handlePhoneWebhook(await request(event,opts),f.options)).status).toBe(401);expect(f.rows).toHaveLength(0);}});
test('non-v1 signatures do not authenticate even when their MAC is otherwise correct',async()=>{const req=await request();req.headers.set('webhook-signature',req.headers.get('webhook-signature')!.replace('v1,','v2,'));const f=deps();expect((await handlePhoneWebhook(req,f.options)).status).toBe(401);expect(f.rows).toHaveLength(0);});
test('GET and oversized bodies do not enter persistence',async()=>{const f=deps();expect((await handlePhoneWebhook(await request(event,{method:'GET'}),f.options)).status).toBe(405);expect((await handlePhoneWebhook(await request('x'.repeat(65537)),f.options)).status).toBe(413);expect(f.rows).toHaveLength(0);});
test('invalid signed JSON or call shape receives a bounded client error',async()=>{for(const body of ['{broken',{},[],{type:'realtime.call.incoming',data:{call_id:42,sip_headers:[]}}]){const f=deps();expect((await handlePhoneWebhook(await request(body),f.options)).status).toBe(400);expect(f.rows).toHaveLength(0);}});
test('unrelated authenticated webhook events are ignored without persistence',async()=>{const f=deps();expect((await handlePhoneWebhook(await request({type:'response.completed'}),f.options)).status).toBe(200);expect(f.rows).toHaveLength(0);});
test('anonymous caller and ambiguous destination are retained as unknown, never guessed',async()=>{const f=deps();const r=await handlePhoneWebhook(await request({...event,data:{...event.data,sip_headers:[{name:'To',value:'sip:+14155550123@a.test'},{name:'To',value:'sip:+14155550125@b.test'},{name:'From',value:'sip:anonymous@anonymous.invalid'}]}}),f.options);expect(r.status).toBe(200);expect(f.rows[0].called_number).toBeNull();expect(f.rows[0].caller_number_hash).toBeNull();expect(f.rows[0].sip_headers).toEqual({});});
test('missing configuration and failed or stalled persistence never acknowledge success',async()=>{for(const override of [{webhookSecret:''},{contactHashKey:''},{persist:async()=>{throw Error('db down')}},{persist:()=>new Promise(()=>{}),persistenceTimeoutMs:10}]){const f=deps(override);expect((await handlePhoneWebhook(await request(),f.options)).status).toBe(503);}});
test('phone canonicalization accepts exact number URIs and rejects hidden alternatives',()=>{for(const value of ['+14155550123','sip:+14155550123@example.test','<sips:+14155550123@example.test;user=phone>','tel:+14155550123'])expect(canonicalPhoneNumber(value)).toBe('+14155550123');for(const value of ['4155550123','sip:proj_test@sip.api.openai.com','sip:+14155550123@a, sip:+14155550124@b','<sip:+14155550123@a>\r\nTo:evil','+14155550123junk','sip:%2B14155550123@example.test'])expect(canonicalPhoneNumber(value)).toBeNull();});

test('provider signing keys are not confused with the fixed-size contact hashing key',async()=>{const signingKey=btoa('a'.repeat(48)),f=deps({webhookSecret:'whsec_'+signingKey});expect((await handlePhoneWebhook(await request(event,{signingKey}),f.options)).status).toBe(200);});
